#!/usr/bin/zsh

# Git
alias gs='git status'
alias ga='git add'
alias gp='git push'
alias gpo='git push origin'
alias gtd='git tag --delete'
alias gtdr='git tag --delete origin'
alias gr='git branch -r'
alias gplo='git pull origin'
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout '
alias gl='git log'
alias gr='git remote'
alias grs='git remote show'
alias glo='git log --pretty="oneline"'
alias glol='git log --graph --oneline --decorate'

# ls
alias ls="lsd --color=always -F --group-directories-first --hyperlink=auto"
alias l="ls"
alias la="ls -a"
alias ll="la -l"

# grep
alias grep="grep --color -i"

# Shell commands
alias rr="source $ZDOTDIR/.zshrc"
mkalias () {
    echo Alias name :
    read alias_name
    echo Command :
    read command_name
    echo alias $alias_name=\"$command_name\" >> $ZDOTDIR/aliases
    source $ZDOTDIR/aliases
}
    
    
cdir () {
    /usr/bin/mkdir $1
    cd $1
}

# Wev
alias w="wev"
alias wk="w -f wl_keyboard"

# Vim
alias vim="nvim"
alias v="nvim"
alias vd="nvim -d"
alias t=task
alias s=sway
alias open=rifle
alias o=open
alias r2c="zathura --page=5 '/home/documents/tristan/Nextcloud/cours/D4/ressources/Arrete R2C/Document PDF.pdf' &"
alias ta='task add'
alias td='t due.before:tomorrow or due:tomorrow'
