#!/usr/bin/zsh

# Git
alias gs='git status'
alias ga='git add'
alias gp='git push'
alias gpo='git push origin'
alias gtd='git tag --delete'
alias gtdr='git tag --delete origin'
alias gr='git branch -r'
alias gplo='git pull origin'
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout '
alias gl='git log'
alias gr='git remote'
alias grs='git remote show'
alias glo='git log --pretty="oneline"'
alias glol='git log --graph --oneline --decorate'

# ls
alias ls="lsd --color -F --group-directories-first"
alias l="ls"
alias la="ls -a"
alias ll="la -l"

# grep
alias grep="grep --color -i"

# Shell commands
alias rr="source $ZDOTDIR/.zshrc"
alias mkalias="vim $ZDOTDIR/aliases"

# Wev
alias w="wev"
alias wk="w -f wl_keyboard"
